import { SiteConfig } from '@/types';

export const siteConfig: SiteConfig = {
  branding: {
    appName: 'Waffle App',
    tagline: 'Descubre salidas, rutas y miradores en moto',
    leadDescription: 'Salidas abiertas cerca de ti, caminos y miradores que no salen en un mapa cualquiera, y una comunidad motociclista con la que rodar. Gratis.',
    subLeadDescription: 'No es solo un GPS. Es donde decides a dónde ir, cuándo y con quién. Diseñado para disfrutar cada curva de la carretera.',
    targetAudience: 'App para motociclistas',
    accentColor: '#22c55e',
    country: 'Chile & Latinoamérica',
  },
  appStoreLinks: {
    iosAppStoreUrl: 'https://apps.apple.com/app/waffle-app',
    googlePlayUrl: 'https://play.google.com/store/apps/details?id=com.waffleapp.app',
    directApkUrl: '#',
    webPlannerUrl: '/plan',
  },
  navigation: [
    { label: 'Home', href: '/' },
    { label: 'Rutas', href: '/#rutas' },
    { label: 'Por qué Waffle', href: '/#por-que' },
    { label: 'Funciones', href: '/#funciones' },
    { label: 'Preguntas', href: '/#faq' },
    { label: 'Planificador de Curvas', href: '/plan', highlight: true },
    { label: 'Descargar App', href: '/#descargar', isDownload: true },
  ],
  definition: {
    lead: 'Waffle App es la plataforma definitiva para motociclistas: descubre salidas abiertas a la comunidad, explora rutas panorámicas, miradores y caminos sinuosos, organiza salidas grupales con punto de encuentro, y mantén tu información de emergencia accesible ante cualquier imprevisto.',
    subLead: 'Planifica tus viajes priorizando curvas y paisajes con nuestro planificador web estilo Kurviger y lleva la navegación en tu teléfono.',
    features: [
      'Salidas grupales con fecha, hora, mapa y punto de encuentro',
      'Rutas y caminos filtrables por región, terreno y dificultad',
      'Planificador de curvas web avanzado con exportación GPX',
      'Miradores y puntos de interés con coordenadas GPS exactas',
      'Moto clubes con muro comunitario, fotografías y eventos',
      'Abre la navegación directa en Google Maps, Apple Maps o tu GPS',
      'Ficha médica y contactos de emergencia seguros con acceso auditado',
      'Notificaciones instantáneas si hay cambios de clima u horario en la salida',
      'Salidas privadas y para grupos cerrados mediante código de acceso',
      '100% gratuita, disponible para iOS y Android',
    ],
  },
  whyUs: [
    {
      problem: '“Tengo el fin de semana libre pero no tengo con quién salir.”',
      answer: 'Abres Waffle App y ves las salidas abiertas de tu zona. Te anotas con un clic y llegas al punto de encuentro sin necesidad de conocer a nadie con anticipación.',
    },
    {
      problem: '“No conozco más rutas que las de siempre.”',
      answer: 'Descubre miles de kilómetros de caminos curvos recomendados por moteros que ya los rodaron, con fotos, estado del asfalto y nivel de dificultad.',
    },
    {
      problem: '“Google Maps me lleva por autopista recta y aburrida.”',
      answer: 'Los mapas genéricos solo buscan la línea más rápida. Waffle App y nuestro planificador de curvas encuentran las mejores curvas, puertos de montaña y miradores.',
    },
    {
      problem: '“Organizar salidas por WhatsApp es un caos total.”',
      answer: 'Toda la salida vive en una sola ficha: punto de reunión, hora, dificultad, waypoints del recorrido y lista de inscritos. Si algo cambia, todos reciben alerta.',
    },
    {
      problem: '“Si me pasa algo en la ruta, nadie sabe mis datos médicos.”',
      answer: 'Tu grupo sanguíneo, alergias y contactos de emergencia viajan en tu app, protegidos con acceso rápido de emergencia para tus compañeros de ruta.',
    },
    {
      problem: '“Quiero planificar mi ruta en el computador y pasarla al GPS.”',
      answer: 'Utiliza nuestro planificador web interactivo: añade waypoints, calcula curvas, visualiza la altimetría y exporta el archivo .GPX directo a tu moto o GPS.',
    },
  ],
  featureCards: [
    {
      title: 'Organiza y busca salidas',
      description: 'Vista de mapa interactivo, trazado de ruta, punto de encuentro y requerimientos de cilindrada en un solo lugar.',
      icon: 'MapPin',
    },
    {
      title: 'Planificador de Curvas Kurviger',
      description: 'Elige tu nivel de curvas: Rápido, Curvado o Super Sinuoso. Visualiza altimetría y descarga archivos GPX para Garmin y navegadores.',
      icon: 'Navigation',
    },
    {
      title: 'Información de Emergencia',
      description: 'Ficha médica y teléfonos de contacto protegidos con acceso auditado para que ruedes con total tranquilidad.',
      icon: 'ShieldAlert',
    },
    {
      title: 'Comunidad & Clubes',
      description: 'Crea tu club de motos, comparte fotos de tus salidas y convoca rodadas públicas o privadas con código.',
      icon: 'Users',
    },
  ],
  sampleRoutes: [
    {
      id: 'farellones-valle-nevado',
      title: 'Curvas de Farellones & Valle Nevado',
      subtitle: 'La clásica subida a la cordillera con 40 curvas pronunciadas y vistas panorámicas',
      region: 'Región Metropolitana',
      terrain: 'asfalto',
      difficulty: 'intermedio',
      distanceKm: 92,
      durationHours: 3.5,
      elevationGainM: 2450,
      meetingPoint: 'Bomba Copec La Dehesa / Costanera Norte',
      waypointsCount: 8,
      tags: ['Cordillera', 'Curvas Cerradas', 'Miradores'],
      coordinates: [
        [-33.3644, -70.5186],
        [-33.3551, -70.4721],
        [-33.3562, -70.4132],
        [-33.3648, -70.3639],
        [-33.3533, -70.2815],
      ],
    },
    {
      id: 'cuesta-la-dormida',
      title: 'Cuesta La Dormida — Olmué',
      subtitle: 'Asfalto en excelente estado, curvas continuas y parada obligada de empanadas',
      region: 'Valparaíso / Metropolitana',
      terrain: 'asfalto',
      difficulty: 'intermedio',
      distanceKm: 148,
      durationHours: 4.0,
      elevationGainM: 1850,
      meetingPoint: 'Peaje Lampa, Ruta 5 Norte',
      waypointsCount: 6,
      tags: ['Panorámica', 'Pique Gastronómico', 'Curvas'],
      coordinates: [
        [-33.2842, -70.8711],
        [-33.1512, -70.9984],
        [-33.0567, -71.1215],
        [-33.0012, -71.1856],
      ],
    },
    {
      id: 'cuesta-chacabuco-los-andes',
      title: 'Antigua Cuesta Chacabuco & Valle de Aconcagua',
      subtitle: 'Historia, mirador del monumento y curvas de montaña sin peaje',
      region: 'Valparaíso',
      terrain: 'asfalto',
      difficulty: 'fácil',
      distanceKm: 125,
      durationHours: 3.0,
      elevationGainM: 1280,
      meetingPoint: 'Pronto Copec Ruta 5 Norte km 38',
      waypointsCount: 5,
      tags: ['Turismo', 'Vistas', 'Asfalto'],
      coordinates: [
        [-33.1234, -70.7123],
        [-32.9812, -70.6985],
        [-32.8456, -70.6234],
      ],
    },
    {
      id: 'embalse-el-yeso-cajon-maipo',
      title: 'Cajón del Maipo & Embalse El Yeso',
      subtitle: 'Ruta cordillerana mixta con paisajes turquesa y aire puro de montaña',
      region: 'Región Metropolitana',
      terrain: 'mixto',
      difficulty: 'avanzado',
      distanceKm: 164,
      durationHours: 5.5,
      elevationGainM: 2600,
      meetingPoint: 'Plaza de San José de Maipo',
      waypointsCount: 7,
      tags: ['Ripio', 'Aventura', 'Laguna', 'Fotografía'],
      coordinates: [
        [-33.6421, -70.3541],
        [-33.7214, -70.2152],
        [-33.6765, -70.0894],
      ],
    },
  ],
  faqs: [
    {
      question: '¿Qué es Waffle App y para qué sirve?',
      answer: 'Waffle App es la aplicación y comunidad gratuita para motociclistas. Te ayuda a decidir a dónde salir, encontrar rutas llenas de curvas y paisajes, unirte a salidas abiertas organizadas por otros pilotos o clubes, y viajar seguro con tu ficha de emergencia.',
    },
    {
      question: '¿Cómo funciona el Planificador de Curvas estilo Kurviger?',
      answer: 'Nuestro planificador web te permite trazar rutas personalizadas entre cualquier punto. A diferencia de un GPS común, puedes elegir perfiles que priorizan carreteras con curvas, evitar autopistas monótonas, revisar el perfil de elevación y exportar el archivo .GPX para tu navegador.',
    },
    {
      question: '¿Waffle App es completamente gratuita?',
      answer: 'Sí. Tanto la app móvil como el planificador web son gratuitos, sin necesidad de suscripciones forzosas ni compras ocultas.',
    },
    {
      question: '¿Puedo usar el planificador web en mi teléfono o computadora?',
      answer: 'Totalmente. El sitio web es 100% responsive: puedes planificar cómodamente en tu pantalla grande o directamente desde el navegador de tu smartphone en plena ruta.',
    },
    {
      question: '¿Cómo exporto una ruta a mi GPS o celular?',
      answer: 'Al calcular cualquier ruta en el planificador, haz clic en "Exportar GPX". Podrás descargar el archivo compatible con Garmin, BMW Connected, OsmAnd, Google Earth y la propia Waffle App.',
    },
    {
      question: '¿Necesito registrarme para usar el planificador o ver rutas?',
      answer: 'No. Puedes explorar el catálogo completo de rutas públicas y utilizar el planificador de curvas web sin crear cuenta.',
    },
  ],
  routePlanner: {
    defaultCenter: [-33.4489, -70.6693], // Santiago de Chile
    defaultZoom: 11,
    tileLayer: {
      name: 'OpenStreetMap Carto / Outdoors',
      url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    },
    routingProvider: 'offline_procedural',
  },
  footer: {
    disclaimer: 'Waffle App es una iniciativa pensada para promover el turismo seguro, la camaradería motera y el disfrute responsable de las carreteras.',
    contactEmail: 'contacto@waffleapp.org',
    copyrightYear: 2026,
  },
};
